# https://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "3.6"
  # PyPy versions
  - "pypy3.5"
  # pip 9.0.1 from /global/software/sl-7.x86_64/modules/langs/python/3.6/lib/python3.6/site-packages (python 3.6) # brc
pip:
  - "9.0.1"
# command to install dependencies
# req could be generated as "pip freeze > requirements.txt", but brc pip is pretty old and travis ci can't find the old packages :(
install: 
  #- pip install --user -r requirements.txt # Can not perform a '--user' install. User site-packages are not visible in this virtualenv. # (python 3.6)
  - pip install -r requirements.txt
  #- pip install .
#command to run tests
script: python bofhbot.py --version
